export const carts = [
  {
    name: 'Pizza Hải Sản Cao Cấp',
    extendName: 'Kích thước Nhỏ 6” - Đế Dày',
    image: 'https://thepizzacompany.vn/images/thumbs/000/0002214_sf-deluxe_300.png',
    description: 'Tôm, cua, mực và nghêu với sốt Marinara',
    price: 159000,
    quantity: 1,
  },
  {
    name: 'Pizza Thịt Xông Khói',
    extendName: 'Kích thước Vừa 9” - Đế Dày',
    image: 'https://thepizzacompany.vn/images/thumbs/000/0002221_bacon-sup_500.png',
    description: 'Thịt giăm bông, thịt xông khói và hai loại rau của ớt xanh, cà chua',
    price: 339000,
    quantity: 2,
  },
  {
    name: 'Pizza Thịt Xông Khói',
    extendName: 'Kích thước Vừa 9” - Đế Dày',
    image: 'https://thepizzacompany.vn/images/thumbs/000/0002221_bacon-sup_500.png',
    description: 'Thịt giăm bông, thịt xông khói và hai loại rau của ớt xanh, cà chua',
    price: 339000,
    quantity: 1,
  },
  {
    name: 'Pizza Hải Sản Cao Cấp',
    extendName: 'Kích thước Nhỏ 6” - Đế Dày',
    image: 'https://thepizzacompany.vn/images/thumbs/000/0002214_sf-deluxe_300.png',
    description: 'Tôm, cua, mực và nghêu với sốt Marinara',
    price: 159000,
    quantity: 4,
  },
  {
    name: 'Pizza Thịt Xông Khói',
    extendName: 'Kích thước Vừa 9” - Đế Dày',
    image: 'https://thepizzacompany.vn/images/thumbs/000/0002221_bacon-sup_500.png',
    description: 'Thịt giăm bông, thịt xông khói và hai loại rau của ớt xanh, cà chua',
    price: 339000,
    quantity: 2,
  },
  {
    name: 'Pizza Thịt Xông Khói',
    extendName: 'Kích thước Vừa 9” - Đế Dày',
    image: 'https://thepizzacompany.vn/images/thumbs/000/0002221_bacon-sup_500.png',
    description: 'Thịt giăm bông, thịt xông khói và hai loại rau của ớt xanh, cà chua',
    price: 339000,
    quantity: 1,
  },
  {
    name: 'Pizza Hải Sản Cao Cấp',
    extendName: 'Kích thước Nhỏ 6” - Đế Dày',
    image: 'https://thepizzacompany.vn/images/thumbs/000/0002214_sf-deluxe_300.png',
    description: 'Tôm, cua, mực và nghêu với sốt Marinara',
    price: 159000,
    quantity: 7,
  },
  {
    name: 'Pizza Thịt Xông Khói',
    extendName: 'Kích thước Vừa 9” - Đế Dày',
    image: 'https://thepizzacompany.vn/images/thumbs/000/0002221_bacon-sup_500.png',
    description: 'Thịt giăm bông, thịt xông khói và hai loại rau của ớt xanh, cà chua',
    price: 339000,
    quantity: 1,
  },
  {
    name: 'Pizza Thịt Xông Khói',
    extendName: 'Kích thước Vừa 9” - Đế Dày',
    image: 'https://thepizzacompany.vn/images/thumbs/000/0002221_bacon-sup_500.png',
    description: 'Thịt giăm bông, thịt xông khói và hai loại rau của ớt xanh, cà chua',
    price: 339000,
    quantity: 1,
  },
];
