const configEnv = {
  API_BASE_URL: process.env.EXPO_PUBLIC_API_BASE_URL,
  OAUTH_CLIENT_ID_WEB: process.env.EXPO_PUBLIC_OAUTH_CLIENT_ID_WEB,
  OAUTH_CLIENT_ID_IOS: process.env.EXPO_PUBLIC_OAUTH_CLIENT_ID_IOS,
  OAUTH_CLIENT_ID_ANDROID: process.env.EXPO_PUBLIC_OAUTH_CLIENT_ID_ANDROID,
};

export default configEnv;
