export { default as FAQsScreen } from './FAQsScreen';
export { default as HomeScreen } from './HomeScreen';
export { default as VoucherScreen } from './VoucherScreen';
export { default as FeedbackScreen } from './FeedbackScreen';
export { default as MyProfileScreen } from './MyProfileScreen';
export { default as OrderDetailScreen } from './OrderDetailScreen';
export { default as AddressSavedScreen } from './AddressSavedScreen';
export { default as NotificationScreen } from './NotificationScreen';
export { default as OrderHistoryScreen } from './OrderHistoryScreen';
export { default as UpdateProfileScreen } from './UpdateProfileScreen';
export { default as AddressUpdateScreen } from './AddressUpdateScreen';
export { default as PrivacyPolicyScreen } from './PrivacyPolicyScreen';
export { default as CategoryScreen } from './ProductCategoryScreens/CategoryScreen';
export { default as ProductDetailScreen } from './ProductCategoryScreens/ProductDetailScreen';
export { default as SignInScreen } from './AuthenticationScreens/SignInScreen';
export { default as TermAndConditionsScreen } from './TermAndConditionsScreen';
export { default as NutritionInformationScreen } from './NutritionInformationScreen';
export { default as DeliveryAndPickupScreen } from './DeliveryAndPickupScreen';
export { default as VerifyOTPScreen } from './AuthenticationScreens/VerifyOTPScreen';
export { default as CartScreen } from './CartScreen';
export { default as OrderInformationScreen } from './OrderScreens/OrderInformationScreen';
export { default as OrderStoreToPickUpScreen } from './OrderScreens/OrderStoreToPickUpScreen';
export { default as OrderPaymentInformationScreen } from './OrderScreens/OrderPaymentInformationScreen';

// import { lazy } from "react";

// export const FAQsScreen = lazy(() => import('./FAQsScreen'))
// export const HomeScreen = lazy(() => import('./HomeScreen'))
// export const VoucherScreen = lazy(() => import('./VoucherScreen'))
// export const FeedbackScreen = lazy(() => import('./FeedbackScreen'))
// export const MyProfileScreen = lazy(() => import('./MyProfileScreen'))
// export const OrderDetailScreen = lazy(() => import('./OrderDetailScreen'))
// export const AddressSavedScreen = lazy(() => import('./AddressSavedScreen'))
// export const NotificationScreen = lazy(() => import('./NotificationScreen'))
// export const OrderHistoryScreen = lazy(() => import('./OrderHistoryScreen'))
// export const UpdateProfileScreen = lazy(() => import('./UpdateProfileScreen'))
// export const AddressUpdateScreen = lazy(() => import('./AddressUpdateScreen'))
// export const PrivacyPolicyScreen = lazy(() => import('./PrivacyPolicyScreen'))
// export const CategoryScreen = lazy(() => import('./ProductCategoryScreens/CategoryScreen'))
// export const ProductDetailScreen = lazy(() => import('./ProductCategoryScreens/ProductDetailScreen'))
// export const SignInScreen = lazy(() => import('./AuthenticationScreens/SignInScreen'))
// export const TermAndConditionsScreen = lazy(() => import('./TermAndConditionsScreen'))
// export const NutritionInformationScreen = lazy(() => import('./NutritionInformationScreen'))
// export const DeliveryAndPickupScreen = lazy(() => import('./DeliveryAndPickupScreen'))
// export const VerifyOTPScreen = lazy(() => import('./AuthenticationScreens/VerifyOTPScreen'))
// export const CartScreen = lazy(() => import('./CartScreen'))
// export const OrderInformationScreen = lazy(() => import('./OrderScreens/OrderInformationScreen'))
// export const OrderStoreToPickUpScreen = lazy(() => import('./OrderScreens/OrderStoreToPickUpScreen'))
