export enum PATH_SCREEN {
  // Authentication
  SIGN_IN_SCREEN = 'SIGN_IN_SCREEN',

  // Home
  HOME_SCREEN = 'HOME_SCREEN',
  ORDER_SCREEN = 'ORDER_SCREEN',

  // Store
  STORE_SCREEN = 'STORE_SCREEN',
  STORE_DETAIL_SCREEN = 'STORE_DETAIL_SCREEN',

  // Cart
  CART_SCREEN = 'CART_SCREEN',

  ORDER_INFORMATION_SCREEN = 'ORDER_INFORMATION_SCREEN',

  ORDER_STORE_TO_PICK_UP_SCREEN = 'ORDER_STORE_TO_PICK_UP_SCREEN',
  ORDER_PAYMENT_RESULT_SCREEN = 'ORDER_PAYMENT_RESULT_SCREEN',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',

  ABOUT_US_SCREEN = 'ABOUT_US_SCREEN',
  DELIVERY_SCREEN = 'DELIVERY_SCREEN',
  FEEDBACK_SCREEN = 'FEEDBACK_SCREEN',
  TERM_AND_CONDITIONS_SCREEN = 'TERM_AND_CONDITIONS_SCREEN',
  FAQS_SCREEN = 'FAQS_SCREEN',
  PRIVACY_POLICY_SCREEN = 'PRIVACY_POLICY_SCREEN',
  NUTRITION_INFORMATION_SCREEN = 'NUTRITION_INFORMATION_SCREEN',
  ADDRESS_UPDATE_SCREEN = 'ADDRESS_UPDATE_SCREEN',
  ORDER_HISTORY_SCREEN = 'ORDER_HISTORY_SCREEN',
  NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN',
  ORDER_DETAIL_SCREEN = 'ORDER_DETAIL_SCREEN',
  DELIVERY_AND_PICKUP_SCREEN = 'DELIVERY_AND_PICKUP_SCREEN',
  PRODUCT_DETAIL_SCREEN = 'PRODUCT_DETAIL_SCREEN',
  MY_PROFILE_SCREEN = 'MY_PROFILE_SCREEN',
  UPDATE_PROFILE_SCREEN = 'UPDATE_PROFILE_SCREEN',
  ADDRESS_SAVED_SCREEN = 'ADDRESS_SAVED_SCREEN',
  CATEGORIES_SCREEN = 'CATEGORIES_SCREEN',
  VOUCHER_SCREEN = 'VOUCHER_SCREEN',
  VERIFY_OTP_SCREEN = 'VERIFY_OTP_SCREEN',
}
