export enum PATH_SCREEN {
  // Authentication
  SIGN_IN_SCREEN = 'SIGN_IN_SCREEN',
  REGISTER_SCREEN = 'REGISTER_SCREEN',

  // Main
  MAIN = 'MAIN',

  // Home
  HOME_SCREEN = 'HOME_SCREEN',
  ORDER_SCREEN = 'ORDER_SCREEN',
  PROMOTION_SCREEN = 'PROMOTION_SCREEN',
  OTHER_SCREEN = 'OTHER_SCREEN',

  // Categories
  CATEGORIES = 'CATEGORIES',

  // Product Detail
  PRODUCT_DETAIL = 'PRODUCT_DETAIL',

  // Store
  STORE_SCREEN = 'STORE_SCREEN',
  STORE_DETAIL_SCREEN = 'STORE_DETAIL_SCREEN',

  ABOUT_US_SCREEN = 'ABOUT_US_SCREEN',
  DELIVERY_SCREEN = 'DELIVERY_SCREEN',
  FEEDBACK_SCREEN = 'FEEDBACK_SCREEN',
  TERM_AND_CONDITIONS_SCREEN = 'TERM_AND_CONDITIONS_SCREEN',
  FAQS_SCREEN = 'FAQS_SCREEN',
  PRIVACY_POLICY_SCREEN = 'PRIVACY_POLICY_SCREEN',
  NUTRITION_INFORMATION_SCREEN = 'NUTRITION_INFORMATION_SCREEN',
  MY_PROFILE = 'MY_PROFILE',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  ADDRESS_SAVED = 'ADDRESS_SAVED',
  ADDRESS_UPDATE_SCREEN = 'ADDRESS_UPDATE_SCREEN',
  ORDER_HISTORY_SCREEN = 'ORDER_HISTORY_SCREEN',
  NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN',
  ORDER_DETAIL_SCREEN = 'ORDER_DETAIL_SCREEN',
}
