export enum PATH_SCREEN {
    // Authentication
    SIGN_IN_SCREEN = 'SIGN_IN_SCREEN',
    REGISTER_SCREEN = 'REGISTER_SCREEN',

    // Main
    MAIN = 'MAIN',

    // Home
    HOME_SCREEN = 'HOME_SCREEN',
    ORDER_SCREEN = 'ORDER_SCREEN',
    PROMOTION_SCREEN = 'PROMOTION_SCREEN',
    OTHER_SCREEN = 'OTHER_SCREEN',

    // Store
    STORE_SCREEN = 'STORE_SCREEN',
    STORE_DETAIL_SCREEN = 'STORE_DETAIL_SCREEN',

    // Notification
    NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN',

    // Promotion
    MY_PROMOTION_SCREEN = 'MY_PROMOTION_SCREEN',
    PROMOTION_DETAIL_SCREEN = 'PROMOTION_DETAIL_SCREEN',

    EXCHANGE_POINT_DETAIL_SCREEN = 'EXCHANGE_POINT_DETAIL_SCREEN',

    ABOUT_US_SCREEN = "ABOUT_US_SCREEN",
    DELIVERY_SCREEN = "DELIVERY_SCREEN"
}
