export enum QUERY_KEY {
    USER = "USER",
    PRODUCT = "PRODUCT",
    LOCATION = 'LOCATION',
    ALL_BANNER = "ALL_BANNER",
    CATEGORIES = "CATEGORIES",
    ALL_CATEGORIES = "ALL_CATEGORIES",
    TERMS_AND_POLICIES = "TERMS_AND_POLICIES",
    USER_ADDRESS = "USER_ADDRESS"
}
